(()=>{"use strict";
const KEY="moneyflow-v2";const $=id=>document.getElementById(id);const pad=n=>String(n).padStart(2,"0");const d0=new Date();const today=`${d0.getFullYear()}-${pad(d0.getMonth()+1)}-${pad(d0.getDate())}`;
const defaults=[
 {name:"Food & Drinks",type:"expense"},{name:"Transportation",type:"expense"},{name:"Family",type:"expense"},{name:"Household",type:"expense"},{name:"Utilities",type:"expense"},{name:"Shopping",type:"expense"},{name:"Health",type:"expense"},{name:"Education",type:"expense"},{name:"Entertainment",type:"expense"},{name:"Rent",type:"expense"},{name:"Salary",type:"income"},{name:"Bonus",type:"income"},{name:"Other Income",type:"income"},{name:"Bank Loan",type:"loan"},{name:"Car Loan",type:"loan"},{name:"Other Loan",type:"loan"},{name:"Credit Card",type:"credit"},{name:"Other Credit",type:"credit"}
];
let state=load();let month=today.slice(0,7);let formType="expense";$("month").value=month;$("date").value=today;
function load(){try{const x=JSON.parse(localStorage.getItem(KEY));if(x&&x.categories&&x.transactions)return x}catch{}return{incomes:{},transactions:[],categories:defaults};}
function save(){localStorage.setItem(KEY,JSON.stringify(state));}
function money(n){return `${Math.round(n).toLocaleString("en-US")} MMK`;}
function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));}
function txMonth(){return state.transactions.filter(x=>x.date.slice(0,7)===month);}
function totals(){const tx=txMonth();const income=tx.filter(x=>x.type==="income").reduce((s,x)=>s+x.amount,0)+Number(state.incomes[month]||0);const expense=tx.filter(x=>x.type==="expense").reduce((s,x)=>s+x.amount,0);const loan=tx.filter(x=>x.type==="loan").reduce((s,x)=>s+x.amount,0);const credit=tx.filter(x=>x.type==="credit").reduce((s,x)=>s+x.amount,0);return{tx,income,expense,loan,credit,remaining:income-expense-loan-credit};}
function render(){const t=totals();$("incomeTotal").textContent=money(t.income);$("expenseTotal").textContent=money(t.expense);$("loanTotal").textContent=money(t.loan);$("creditTotal").textContent=money(t.credit);$("remaining").textContent=money(t.remaining);const committed=t.expense+t.loan+t.credit;const pct=t.income?Math.min(100,Math.max(0,committed/t.income*100)):0;const saveRate=t.income?t.remaining/t.income*100:0;$("balanceProgress").style.width=pct+"%";$("usedText").textContent=pct.toFixed(1)+"% committed";$("saveText").textContent=saveRate.toFixed(1)+"% savings rate";$("statusPill").textContent=t.remaining>=0?"Positive balance":"Over budget";$("statusPill").style.background=t.remaining>=0?"rgba(34,197,94,.16)":"rgba(239,68,68,.18)";renderBreakdown(t);renderRecent(t.tx);renderAnalysis(t);renderRows(t.tx);}
function renderBreakdown(t){const groups={};t.tx.filter(x=>x.type!=="income").forEach(x=>groups[x.category]=(groups[x.category]||0)+x.amount);const items=Object.entries(groups).sort((a,b)=>b[1]-a[1]);const total=t.expense+t.loan+t.credit;$("breakdown").innerHTML=items.length?items.slice(0,7).map(([n,v])=>`<div class="break-item"><div class="break-head"><span>${esc(n)}</span><b>${money(v)}</b></div><div class="bar"><i style="width:${total?v/total*100:0}%"></i></div></div>`).join(""):`<p class="muted">No spending recorded this month.</p>`;}
function icon(type){return type==="income"?"↗":type==="loan"?"↘":type==="credit"?"◈":"−";}
function typeName(type){return type==="income"?"Income":type==="loan"?"Loan Payment":type==="credit"?"Credit Payback":"Expense";}
function renderRecent(tx){const arr=[...tx].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,5);$("recent").innerHTML=arr.length?arr.map(x=>`<div class="activity"><div class="activity-icon">${icon(x.type)}</div><div class="activity-main"><b>${esc(x.note||x.category)}</b><span>${typeName(x.type)} · ${esc(x.date)}</span></div><div class="activity-amount ${x.type}-text">${x.type==="income"?"+":"−"}${money(x.amount)}</div></div>`).join(""):`<p class="muted">No activity yet.</p>`;}
function renderAnalysis(t){$("analysisFlow").innerHTML=`<div class="activity"><span>Income</span><b class="income-text">+${money(t.income)}</b></div><div class="activity"><span>Living expenses</span><b class="expense-text">−${money(t.expense)}</b></div><div class="activity"><span>Bank / loans</span><b class="loan-text">−${money(t.loan)}</b></div><div class="activity"><span>Credit paybacks</span><b class="credit-text">−${money(t.credit)}</b></div><div class="activity"><span><strong>Remaining</strong></span><b>${money(t.remaining)}</b></div>`;const groups={};t.tx.filter(x=>x.type!=="income").forEach(x=>groups[x.category]=(groups[x.category]||0)+x.amount);const total=t.expense+t.loan+t.credit;$("analysisCats").innerHTML=Object.entries(groups).sort((a,b)=>b[1]-a[1]).map(([n,v])=>`<div class="break-item"><div class="break-head"><span>${esc(n)}</span><b>${money(v)}</b></div><div class="bar"><i style="width:${total?v/total*100:0}%"></i></div></div>`).join("")||'<p class="muted">No spending recorded.</p>';}
function renderRows(tx){const arr=[...tx].sort((a,b)=>b.date.localeCompare(a.date));$("txCount").textContent=`${arr.length} transaction${arr.length===1?"":"s"}`;$("txRows").innerHTML=arr.length?arr.map(x=>`<tr><td>${esc(x.date)}</td><td><b>${typeName(x.type)}</b><br><span class="muted">${esc(x.note||x.category)}</span></td><td class="${x.type}-text">${x.type==="income"?"+":"−"}${money(x.amount)}</td><td><button data-del="${x.id}">✕</button></td></tr>`).join(""):'<tr><td colspan="4" class="muted">No transactions.</td></tr>';}
function categoriesFor(type){return state.categories.filter(x=>x.type===type);}
function refreshCategorySelect(){const list=categoriesFor(formType);$("category").innerHTML=list.length?list.map(x=>`<option>${esc(x.name)}</option>`).join(""):'<option>Uncategorized</option>';}
function setFormType(type){formType=type;document.querySelectorAll("[data-formtype]").forEach(b=>b.classList.toggle("active",b.dataset.formtype===type));$("formTitle").textContent={expense:"Add Expense",income:"Add Income",loan:"Loan Payment",credit:"Credit Payback"}[type];refreshCategorySelect();}
function show(page){document.querySelectorAll(".page").forEach(p=>p.classList.toggle("active",p.id===page));document.querySelectorAll(".bottom-nav [data-page]").forEach(b=>b.classList.toggle("active",b.dataset.page===page));if(page==="settings")renderSettings();if(page==="analysis")render();window.scrollTo(0,0);}
function toast(msg){$("toast").textContent=msg;$("toast").classList.add("show");setTimeout(()=>$("toast").classList.remove("show"),1800);}
document.addEventListener("click",e=>{const p=e.target.closest("[data-page]");if(p)show(p.dataset.page);const a=e.target.closest("[data-add]");if(a){setFormType(a.dataset.add);show("add");}const ft=e.target.closest("[data-formtype]");if(ft)setFormType(ft.dataset.formtype);const del=e.target.closest("[data-del]");if(del){state.transactions=state.transactions.filter(x=>String(x.id)!==del.dataset.del);save();render();toast("Transaction deleted");}const catdel=e.target.closest("[data-catdel]");if(catdel){const i=Number(catdel.dataset.catdel);state.categories.splice(i,1);save();renderSettings();refreshCategorySelect();toast("Category deleted");}});
$("month").addEventListener("change",e=>{month=e.target.value||month;render();});
$("txForm").addEventListener("submit",e=>{e.preventDefault();const amount=Number($("amount").value),date=$("date").value;if(!date||!Number.isFinite(amount)||amount<=0)return toast("Enter a valid amount");month=date.slice(0,7);$("month").value=month;state.transactions.push({id:`${Date.now()}-${Math.random()}`,date,amount,type:formType,category:$("category").value,note:$("note").value.trim()});save();$("amount").value="";$("note").value="";render();toast("Transaction saved");show("home");});
$("clearBtn").addEventListener("click",()=>{if(confirm("Delete all transactions and income records?")){state={incomes:{},transactions:[],categories:defaults};save();render();toast("All data cleared");}});
function renderSettings(){const types=["expense","income","loan","credit"];const names={expense:"Expense",income:"Income",loan:"Loan",credit:"Credit Payback"};$("categoryLists").innerHTML=types.map(type=>`<div class="category-group"><h3>${names[type]}</h3>${state.categories.map((c,i)=>c.type===type?`<div class="cat-row"><span class="cat-name">${esc(c.name)}</span><span class="cat-type">${names[c.type]}</span><button data-catdel="${i}" aria-label="Delete category">✕</button></div>`:"").join("")||'<span class="muted">No categories.</span>'}</div>`).join("");}
$("addCat").addEventListener("click",()=>{const name=$("newCat").value.trim(),type=$("newCatType").value;if(!name)return toast("Enter a category name");if(state.categories.some(c=>c.type===type&&c.name.toLowerCase()===name.toLowerCase()))return toast("Category already exists");state.categories.push({name,type});save();$("newCat").value="";renderSettings();refreshCategorySelect();toast("Category added");});
$("exportBtn").addEventListener("click",()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`moneyflow-backup-${month}.json`;a.click();URL.revokeObjectURL(a.href);});
$("importFile").addEventListener("change",async e=>{const file=e.target.files[0];if(!file)return;try{const imported=JSON.parse(await file.text());if(!imported.categories||!imported.transactions)throw Error();state=imported;save();refreshCategorySelect();render();renderSettings();toast("Backup imported");}catch{toast("Invalid backup file");}e.target.value="";});
let deferred=null;window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferred=e;$("installBtn").classList.remove("hidden")});$("installBtn").addEventListener("click",async()=>{if(!deferred)return;deferred.prompt();await deferred.userChoice;deferred=null;$("installBtn").classList.add("hidden")});
if("serviceWorker"in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("sw.js").catch(console.warn));
setFormType("expense");render();
})();