const SPREADSHEET_ID="";
function ss(){return SPREADSHEET_ID?SpreadsheetApp.openById(SPREADSHEET_ID):SpreadsheetApp.getActiveSpreadsheet()}
function out(o){return ContentService.createTextOutput(JSON.stringify(o)).setMimeType(ContentService.MimeType.JSON)}
function doGet(){return out({ok:true,message:"MoneyFlow Apps Script is online"})}
function doPost(e){try{let r=JSON.parse(e.postData.contents||"{}");if(r.action==="ping")return out({ok:true,message:"Connected to Google Sheets"});if(r.action==="getAll")return out({ok:true,data:readAll()});if(r.action==="replaceAll"){writeAll(r.payload||{});return out({ok:true,count:(r.payload?.transactions||[]).length})}return out({ok:false,error:"Unknown action"})}catch(x){return out({ok:false,error:String(x)})}}
function sheet(n,h){let s=ss().getSheetByName(n)||ss().insertSheet(n);if(s.getLastRow()===0)s.getRange(1,1,1,h.length).setValues([h]);return s}
function rows(n,h){let v=sheet(n,h).getDataRange().getValues();return v.length<2?[]:v.slice(1).filter(r=>r.some(x=>x!=="")).map(r=>Object.fromEntries(h.map((k,i)=>[k,r[i]])))}
function readAll(){let transactions=rows("Transactions",["id","type","amount","date","category","note","createdAt"]).map(x=>({id:String(x.id),type:String(x.type),amount:Number(x.amount||0),date:x.date instanceof Date?Utilities.formatDate(x.date,Session.getScriptTimeZone(),"yyyy-MM-dd"):String(x.date).slice(0,10),category:String(x.category),note:String(x.note||""),createdAt:String(x.createdAt||"")}));let incomes={};rows("Incomes",["month","amount"]).forEach(x=>incomes[String(x.month)]=Number(x.amount||0));let categories=rows("Categories",["name","type"]).map(x=>({name:String(x.name),type:String(x.type)}));return{transactions,incomes,categories}}
function writeAll(p){table("Transactions",["id","type","amount","date","category","note","createdAt"],(p.transactions||[]).map(x=>[x.id,x.type,Number(x.amount||0),x.date,x.category,x.note||"",x.createdAt||""]));table("Incomes",["month","amount"],Object.keys(p.incomes||{}).map(m=>[m,Number(p.incomes[m]||0)]));table("Categories",["name","type"],(p.categories||[]).map(x=>[x.name,x.type]))}
function table(n,h,r){let s=sheet(n,h);s.clearContents();s.getRange(1,1,1,h.length).setValues([h]);if(r.length)s.getRange(2,1,r.length,h.length).setValues(r);s.setFrozenRows(1)}